name: Cucumber Allure tests CI - manual (Standalone browser)

on:
  workflow_call:
    inputs:
      BROWSER:
        type: string

  workflow_dispatch:
    inputs:
      BROWSER:
        type: choice
        required: true
        description: Select supported browser
        options:
          - chrome
          - firefox
          - edge
        default: chrome

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@latest

      - name: Setup JDK 17
        uses: actions/setup-java@latest
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Install dependencies
        id: setup_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2

      - name: Install Chrome
        id: setup_chrome
        if: ${{ inputs.BROWSER == 'chrome' }}
        uses: browser-actions/setup-chrome@latest
      - name: Print Chrome version
        if: ${{ inputs.BROWSER == 'chrome' }}
        run: chrome --version

      - name: Install Firefox
        id: setup_firefox
        if: ${{ inputs.BROWSER == 'firefox' }}
        uses: browser-actions/setup-firefox@latest
      - name: Print Firefox version
        if: ${{ inputs.BROWSER == 'firefox' }}
        run: firefox --version

      - name: Install Edge
        id: setup_edge
        if: ${{ inputs.BROWSER == 'edge' }}
        uses: browser-actions/setup-edge@latest
      - name: Print Edge version
        if: ${{ inputs.BROWSER == 'edge' }}
        run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion

      - name: Build and Test with Gradle
        if: always()
        run: |
          ./gradlew clean test -Dselenide.headless=false -Dselenide.browser="${{ inputs.BROWSER }}"
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

