name: Cucumber Allure tests CI - manual (Standalone browser)

on:
  workflow_call:
    inputs:
      BROWSER:
        type: string

  workflow_dispatch:
    inputs:
      BROWSER:
        type: choice
        required: true
        description: Select supported browser
        options:
          - chrome
          - firefox
          - edge
        default: chrome

permissions:
  contents: write
  pages: write
  id-token: write
  checks: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      BROWSER: ${{ steps.prepare.outputs.BROWSER }}
      ALLURE_LINK: ${{ steps.prepare.outputs.ALLURE_LINK }}

    steps:
      - name: Prepare
        id: prepare
        run: |
          echo "BROWSER=${{ inputs.BROWSER }}" >> $GITHUB_OUTPUT
          echo "ALLURE_LINK=https://mrc81.github.io/Cucumber_Selenide" >> $GITHUB_OUTPUT

      - name: Adding markdown
        run: |
          echo "- BROWSER: ${{ steps.prepare.outputs.BROWSER }}" >> $GITHUB_STEP_SUMMARY

  run_tests:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Install dependencies
        id: setup_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2

      - name: Install Chrome
        id: setup_chrome
        if: ${{ inputs.BROWSER == 'chrome' }}
        uses: browser-actions/setup-chrome@v1
      - name: Print Chrome version
        if: ${{ inputs.BROWSER == 'chrome' }}
        run: chrome --version

      - name: Install Firefox
        id: setup_firefox
        if: ${{ inputs.BROWSER == 'firefox' }}
        uses: browser-actions/setup-firefox@v1
      - name: Print Firefox version
        if: ${{ inputs.BROWSER == 'firefox' }}
        run: firefox --version

      - name: Install Edge
        id: setup_edge
        if: ${{ inputs.BROWSER == 'edge' }}
        uses: browser-actions/setup-edge@v1
      - name: Print Edge version
        if: ${{ inputs.BROWSER == 'edge' }}
        run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion

      - name: Build and Test with Gradle
        if: always()
        run: |
          ./gradlew clean test -Dselenide.headless=true -Dselenide.browser="${{ inputs.BROWSER }}"
        continue-on-error: true

      - name: add Env params to Allure report
        shell: bash
        run: |
          echo "BROWSER=${{ inputs.BROWSER }}" >> allure-results/environment.properties

      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Get Allure history
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Adding markdown
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Allure report has been generated" >> $GITHUB_STEP_SUMMARY
          echo "- URL: ${{ needs.prepare.outputs.ALLURE_LINK }}" >> $GITHUB_STEP_SUMMARY