name: Cucumber Allure tests CI (On push run with Chrome)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build and Test with Gradle
        if: always()
        run: |
          ./gradlew clean test -Dselenide.headless=true
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

#      - name: Post the link to the report
#        if: always()
#        uses: Sibz/github-status-action@v1.1.6
#        with:
#          authToken: ${{ secrets.GITHUB_TOKEN }}
#          context: 'Test report'
#          state: 'success'
#          sha: ${{ github.event.pull_request.head.sha }}
#          target_url: https://mrc81.github.io/QAtest_Cucumber/${{ github.run_number }}
