name: Cucumber Allure tests CI (On push run with Chrome)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write
  checks: write

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
      - run: chrome --version

      - name: Get Chrome Version
        id: chrome_version
        run: echo "::set-output name=version::$(chrome --version | cut -d ' ' -f 2 | cut -d '.' -f 1)"

      - name: Build and Test with Gradle 
        if: always() # need to specify the browser version otherwise ChromeDriver fails for the 'latest' version value 
        run: | 
          ./gradlew clean test -Dversion=${{ steps.chrome_version.outputs.version }} -Dselenide.headless=true
        continue-on-error: true

      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Get Allure history
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history